In [84]:
# Data Preprocessing
# importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [85]:
# Importing the dataset
data = pd.read_csv("Data.csv")

data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [86]:
X = data.iloc[:, :-1].values

y = data.iloc[:, -1:].values

In [87]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [88]:
# Take care of missing data
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:3])

X[:, 1:3] = imputer.transform(X[:, 1:3])

In [89]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [61]:
# Encoding Categorical data
# from sklearn.preprocessing import LabelEncoder

# label_encoderX = LabelEncoder()
# X[:, 0] = label_encoderX.fit_transform(X[:, 0])

In [62]:
# Encoding the countries with numeric values could assign some unintended weight to the country one 
#is in making spain greater than germany and france and germany better than france which is not 
# necessarily true
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [50]:
# Deprecated
# from sklearn.preprocessing import OneHotEncoder
# one_hot_encoder = OneHotEncoder(categorical_features = [0])
# X = one_hot_encoder.fit_transform(X).toarray()

In [90]:
# Encoding Categorical Data
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_transformer

preprocess = make_column_transformer(
    (StandardScaler(), [1, 2]),
    (OneHotEncoder(categories='auto'), [0])
)

In [91]:
preprocess.fit_transform(X)


/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 7.58874362e-01,  7.49473254e-01,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-1.71150388e+00, -1.43817841e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00],
       [-1.27555478e+00, -8.91265492e-01,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00],
       [-1.13023841e-01, -2.53200424e-01,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00],
       [ 1.77608893e-01,  6.63219199e-16,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00],
       [-5.48972942e-01, -5.26656882e-01,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.07356980e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00],
       [ 1.34013983e+00,  1.38753832e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.63077256e+00,  1.75214693e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00],
       [-2.58340208e-01,  2.93712492e-01,  1.00000000e+00,
         0.00000000e+00

In [95]:
# encoding y values numeric
from sklearn.preprocessing import LabelEncoder

label_encodery = LabelEncoder()
y = label_encodery.fit_transform(y.ravel())

In [96]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])